# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

sonar.projectKey=NBUSW_Enterprise-AI-Automation_Skill-Evaluator_SkillEvaluator
sonar.projectName=SkillEvaluator
sonar.sourceEncoding=UTF-8

sonar.sources=src,scripts
sonar.tests=tests
sonar.python.version=3.12,3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
